name: Rust

on:
  push:
    tags:        
      - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/stripper"