name: Rust

on:
  push:
    tags:        
      - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: Shopify/upload-to-release@v1.0.1
      with:
        name: stripper
        path: target/release/st
        repo-token: ${{ secrets.GITHUB_TOKEN }}